[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build phase needed'"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
