[providers]
python = "3.11"

[providers.node]
version = false

[build]
nixpkgs = ["python311", "python311Packages.pip", "postgresql"]

[variables]
NODE_ENV = ""
NPM_CONFIG_PRODUCTION = "false"
PORT = "8000"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
  "echo 'Installing Python dependencies with caching...'",
  "pip install --upgrade pip --cache-dir /tmp/pip-cache",
  "pip install -r requirements.txt --cache-dir /tmp/pip-cache --no-compile"
]

[phases.build]
cmds = ["echo 'Python Flask app - no build needed'"]

[start]
cmd = "gunicorn app_debug:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --log-level info"
