[providers]
python = "3.11"

[providers.node]
version = false

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
  "echo 'Installing Python dependencies...'",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python Flask app - no build needed'"]

[start]
cmd = "gunicorn app_prod:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
